export const profile = [
  {
    id: 1,
    name: 'Nozimjon',
    position: 'Junior',
    role: 'Software Developer',
    email: 'emmadorsey@example.com',
    imageUrl: '/images/nozimjon.jpg',
    bio: 'Praesentium iure error aliquam voluptas ut libero. Commodi placeat sit iure nulla officiis. Ut ex sit repellat tempora. Qui est accusamus exercitationem natus ut voluptas. Officiis velit eos ducimus.',
    about:
      'Fugiat ipsum ipsum deserunt culpa aute sint do nostrud anim incididunt cillum culpa consequat. Excepteur qui ipsum aliquip consequat sint. Sit id mollit nulla mollit nostrud in ea officia proident. Irure nostrud pariatur mollit ad adipisicing reprehenderit deserunt qui eu.',
    benefits: [
      'C#',
      'ASP.NET Core Web API',
      'ASP.NET Core MVC',
      'MS SQL Server',
      'PostgreSQL',
      'LINQ',
      'REST',
      'GraphQL',
      'Unit Testing',
      'Design Principles and Patterns',
    ],
    twitterUrl: '#',
    linkedinUrl: '#',
  },
  {
    id: 2,
    name: 'Saidnabi',
    position: 'Junior',
    role: 'Software Developer',
    email: 'emmadorsey@example.com',
    imageUrl: '/images/saidnabi.jpg',
    bio: 'Praesentium iure error aliquam voluptas ut libero. Commodi placeat sit iure nulla officiis. Ut ex sit repellat tempora. Qui est accusamus exercitationem natus ut voluptas. Officiis velit eos ducimus.',
    about:
      'Fugiat ipsum ipsum deserunt culpa aute sint do nostrud anim incididunt cillum culpa consequat. Excepteur qui ipsum aliquip consequat sint. Sit id mollit nulla mollit nostrud in ea officia proident. Irure nostrud pariatur mollit ad adipisicing reprehenderit deserunt qui eu.',
    benefits: [
      'C#',
      'ASP.NET Core Web API',
      'ASP.NET Core MVC',
      'MS SQL Server',
      'PostgreSQL',
      'LINQ',
      'REST',
      'GraphQL',
      'Unit Testing',
      'Design Principles and Patterns',
    ],
    twitterUrl: '#',
    linkedinUrl: '#',
  },
  {
    id: 3,
    name: 'Behzodkhoja',
    position: 'Junior',
    role: 'Software Developer',
    email: 'emmadorsey@example.com',
    imageUrl: '/images/begzod.jpg',
    bio: 'Praesentium iure error aliquam voluptas ut libero. Commodi placeat sit iure nulla officiis. Ut ex sit repellat tempora. Qui est accusamus exercitationem natus ut voluptas. Officiis velit eos ducimus.',
    about:
      'Fugiat ipsum ipsum deserunt culpa aute sint do nostrud anim incididunt cillum culpa consequat. Excepteur qui ipsum aliquip consequat sint. Sit id mollit nulla mollit nostrud in ea officia proident. Irure nostrud pariatur mollit ad adipisicing reprehenderit deserunt qui eu.',
    benefits: [
      'C#',
      'ASP.NET Core Web API',
      'ASP.NET Core MVC',
      'MS SQL Server',
      'PostgreSQL',
      'LINQ',
      'REST',
      'GraphQL',
      'Unit Testing',
      'Design Principles and Patterns',
    ],
    twitterUrl: '#',
    linkedinUrl: '#',
  },
]
